FROM ydjharbor.jingzhuan.cn/base/golang:1.16.5-alpine AS build-env

# 为我们的镜像设置必要的环境变量
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://goproxy.cn

RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata


# 移动到工作目录：/wwwroot/
WORKDIR /home/wwwroot/

# 将代码复制到容器中
COPY . .

# 将我们的代码编译成二进制可执行文件app
RUN cd main && go build service.go
